/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.liferay.kris.jlr.warranty.model;

import aQute.bnd.annotation.ProviderType;

import com.liferay.expando.kernel.model.ExpandoBridge;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.GroupedModel;
import com.liferay.portal.kernel.model.ShardedModel;
import com.liferay.portal.kernel.model.StagedAuditedModel;
import com.liferay.portal.kernel.service.ServiceContext;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the Warranty service. Represents a row in the &quot;JLR_Warranty&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.liferay.kris.jlr.warranty.model.impl.WarrantyModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.liferay.kris.jlr.warranty.model.impl.WarrantyImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see Warranty
 * @see com.liferay.kris.jlr.warranty.model.impl.WarrantyImpl
 * @see com.liferay.kris.jlr.warranty.model.impl.WarrantyModelImpl
 * @generated
 */
@ProviderType
public interface WarrantyModel extends BaseModel<Warranty>, GroupedModel,
	ShardedModel, StagedAuditedModel {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a warranty model instance should use the {@link Warranty} interface instead.
	 */

	/**
	 * Returns the primary key of this warranty.
	 *
	 * @return the primary key of this warranty
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this warranty.
	 *
	 * @param primaryKey the primary key of this warranty
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the uuid of this warranty.
	 *
	 * @return the uuid of this warranty
	 */
	@AutoEscape
	@Override
	public String getUuid();

	/**
	 * Sets the uuid of this warranty.
	 *
	 * @param uuid the uuid of this warranty
	 */
	@Override
	public void setUuid(String uuid);

	/**
	 * Returns the jlr warranty ID of this warranty.
	 *
	 * @return the jlr warranty ID of this warranty
	 */
	public long getJlrWarrantyId();

	/**
	 * Sets the jlr warranty ID of this warranty.
	 *
	 * @param jlrWarrantyId the jlr warranty ID of this warranty
	 */
	public void setJlrWarrantyId(long jlrWarrantyId);

	/**
	 * Returns the group ID of this warranty.
	 *
	 * @return the group ID of this warranty
	 */
	@Override
	public long getGroupId();

	/**
	 * Sets the group ID of this warranty.
	 *
	 * @param groupId the group ID of this warranty
	 */
	@Override
	public void setGroupId(long groupId);

	/**
	 * Returns the company ID of this warranty.
	 *
	 * @return the company ID of this warranty
	 */
	@Override
	public long getCompanyId();

	/**
	 * Sets the company ID of this warranty.
	 *
	 * @param companyId the company ID of this warranty
	 */
	@Override
	public void setCompanyId(long companyId);

	/**
	 * Returns the user ID of this warranty.
	 *
	 * @return the user ID of this warranty
	 */
	@Override
	public long getUserId();

	/**
	 * Sets the user ID of this warranty.
	 *
	 * @param userId the user ID of this warranty
	 */
	@Override
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this warranty.
	 *
	 * @return the user uuid of this warranty
	 */
	@Override
	public String getUserUuid();

	/**
	 * Sets the user uuid of this warranty.
	 *
	 * @param userUuid the user uuid of this warranty
	 */
	@Override
	public void setUserUuid(String userUuid);

	/**
	 * Returns the user name of this warranty.
	 *
	 * @return the user name of this warranty
	 */
	@AutoEscape
	@Override
	public String getUserName();

	/**
	 * Sets the user name of this warranty.
	 *
	 * @param userName the user name of this warranty
	 */
	@Override
	public void setUserName(String userName);

	/**
	 * Returns the create date of this warranty.
	 *
	 * @return the create date of this warranty
	 */
	@Override
	public Date getCreateDate();

	/**
	 * Sets the create date of this warranty.
	 *
	 * @param createDate the create date of this warranty
	 */
	@Override
	public void setCreateDate(Date createDate);

	/**
	 * Returns the modified date of this warranty.
	 *
	 * @return the modified date of this warranty
	 */
	@Override
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this warranty.
	 *
	 * @param modifiedDate the modified date of this warranty
	 */
	@Override
	public void setModifiedDate(Date modifiedDate);

	/**
	 * Returns the category of this warranty.
	 *
	 * @return the category of this warranty
	 */
	@AutoEscape
	public String getCategory();

	/**
	 * Sets the category of this warranty.
	 *
	 * @param category the category of this warranty
	 */
	public void setCategory(String category);

	/**
	 * Returns the period of this warranty.
	 *
	 * @return the period of this warranty
	 */
	@AutoEscape
	public String getPeriod();

	/**
	 * Sets the period of this warranty.
	 *
	 * @param period the period of this warranty
	 */
	public void setPeriod(String period);

	/**
	 * Returns the dealer of this warranty.
	 *
	 * @return the dealer of this warranty
	 */
	@AutoEscape
	public String getDealer();

	/**
	 * Sets the dealer of this warranty.
	 *
	 * @param dealer the dealer of this warranty
	 */
	public void setDealer(String dealer);

	/**
	 * Returns the part category of this warranty.
	 *
	 * @return the part category of this warranty
	 */
	@AutoEscape
	public String getPartCategory();

	/**
	 * Sets the part category of this warranty.
	 *
	 * @param partCategory the part category of this warranty
	 */
	public void setPartCategory(String partCategory);

	/**
	 * Returns the actual cost of this warranty.
	 *
	 * @return the actual cost of this warranty
	 */
	public int getActualCost();

	/**
	 * Sets the actual cost of this warranty.
	 *
	 * @param actualCost the actual cost of this warranty
	 */
	public void setActualCost(int actualCost);

	/**
	 * Returns the con code of this warranty.
	 *
	 * @return the con code of this warranty
	 */
	@AutoEscape
	public String getConCode();

	/**
	 * Sets the con code of this warranty.
	 *
	 * @param conCode the con code of this warranty
	 */
	public void setConCode(String conCode);

	/**
	 * Returns the percentage of this warranty.
	 *
	 * @return the percentage of this warranty
	 */
	public int getPercentage();

	/**
	 * Sets the percentage of this warranty.
	 *
	 * @param percentage the percentage of this warranty
	 */
	public void setPercentage(int percentage);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(Warranty warranty);

	@Override
	public int hashCode();

	@Override
	public CacheModel<Warranty> toCacheModel();

	@Override
	public Warranty toEscapedModel();

	@Override
	public Warranty toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}